export const EMPTY_PRODUCT_FAVORITE_LIST = "EMPTY_PRODUCT_FAVORITE_LIST";
export const GET_PRODUCT_FAVORITE_LIST = "GET_PRODUCT_FAVORITE_LIST";
export const TOGGLE_FAVORITE_LIST = "TOGGLE_FAVORITE_LIST ";
export const ADD_FAVORITE_LIST = "ADD_FAVORITE_LIST";

export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

export const ADD_SHOPPING_CART = "ADD_SHOPPING_CART";
export const REMOVE_SHOPPING_CART = "REMOVE_SHOPPING_CART";
export const GET_SHOPPING_CART = "GET_SHOPPING_CART";
export const EMPTY_SHOPPING_CART = "EMPTY_SHOPPING_CART";