export const ADD_PRODUCT_FAVORITE_LIST = "ADD_PRODUCT_FAVORITE_LIST";
export const REMOVE_PRODUCT_FAVORITE_LIST = "REMOVE_PRODUCT_FAVORITE_LIST";
export const EMPTY_PRODUCT_FAVORITE_LIST = "EMPTY_PRODUCT_FAVORITE_LIST";
export const GET_PRODUCT_FAVORITE_LIST = "GET_PRODUCT_FAVORITE_LIST";
export const TOGGLE_FAVORITE_LIST = "TOGGLE_FAVORITE_LIST ";
export const ADD_FAVORITE_LIST = "ADD_FAVORITE_LIST";

export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";